### PR TITLE
Replace is_it_working with okcomputer

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@cbeer Are you cool with having multiple merge commits in this branch, or would you prefer to rebase on master?

**Comment by cbeer** [comment]
Won't you be forced to make a squash commit anyway?

**Comment by mjgiarlo** [comment]
@cbeer Let's find out.

**Comment by mjgiarlo** [comment]
@cbeer yep, worked like a charm. :tada:

**Pull request merged**
