### PR TITLE
Add the ability to define exhibit based feature flags

### LINKED ISSUE #667: Add the ability to feature flag based on an exhibit
Our current feature flag ability is at the global exhibits level, if we can add exhibit level flags too, this could help us release functionality to specific exhibits sooner.

### PR DESCRIPTION
**Pull request by jkeck**
Closes #667

### CODE REVIEW

**Comment by jkeck** [comment]
Was thinking about pulling this logic that knows how to take a given context (passed through `for`) and return context specific flags to be merged into the base so that this class didn't have to have knowledge of how to get exhibit specific settings.  Happy to follow that through if folks think it's a worthwhile abstraction.

**Comment by jkeck** [comment]
From what I understand a UI for this is out of scope at the moment and I don't believe we have designs.

It seems like creating an active record backed feature flag implementation without a UI to update it would end up being more cumbersome to turn features on/off, or would require tooling to manage that state based on something like settings in the first place.

This implementation could allow for the same or similar API to be carried over once we do have an AR backed implementation.

**Comment by ggeisler** [comment]
Yeah, I was just raising the question of: do we want a UI for feature flags? If the answer is yes, then I will work on a design in a new ticket.

**Comment by mejackreed** [comment]
I was thinking about this. How would a UI for feature flags differ from the admin dashboard? They fill similar enough to me when I was thinking about it (but I may be wrong). I feel like we should trust administrative and curatorial users enough to show them new features as long as we give them proper context and information.

**Comment by ggeisler** [comment]
Yep, we could definitely add it to the Configuration section of the exhibit admin instead. I think we'd want @caaster to weigh in on whether we want to give the power to exhibit admins or whether we want super-admins to control it. I suggested the latter approach because I sort of assumed @caaster might be concerned about individual admins having this control, but I certainly could be wrong about that.

**Pull request merged**
