### PR TITLE
Configure a Parker theme (behind a feature flag).

### LINKED ISSUE #527: Enable theming and omit SUL and SU footers from Parker exhibit site
Based on discussion with @blalbrit, the  Parker use case requires not showing the SUL and SU footers for the Parker exhibit (because they overemphasize Stanford's role in the partnership).

Presumably this would involve a Parker CSS override to simply hide the footer elements from the exhibit when the exhibit is Parker.

If we do this, we will probably be able to not worry about #446.

### PR DESCRIPTION
**Pull request by jkeck**
Closes #527 

See sul-dlss/shared_configs#400 for related PR

admin-ui

exhibit-with-parker-theme

### CODE REVIEW

**Comment by jkeck** [comment]
@ggeisler not sure if you had ideas on the icons we should use.  I've added something for now, happy to change them.

**Comment by ggeisler** [comment]
@mejackreed Looks good for now. If I have improvement ideas I'll use #590 for them.

**Comment by mejackreed** [comment]
LGTM. One minor comment, can we remove the DS_Store file?

**Comment by jkeck** [comment]
Ugh, yeah, sorry, not sure why my global gitignore file is failing me.

**Pull request merged**
