### PR TITLE
Only index collection title in the collection_with_title field.

### LINKED ISSUE #1020: Refactor collection_with_title field to not include the druid
We don't make use of the druid part of this field and have to provide helper methods handle the field parsing.  Since we own our own indexing logic completely now, we don't need to have this compound field (which is a holdover from the SearchWorks indexing pipeline).

### LINKED ISSUE #1029: Collection facet not showing collection name
I imagine this has to do w/ #1004

We'll need to address this (possibly by doing #1020), or revert that PR before our next release.

On exhibits-stage:
colection-facet-bug

### PR DESCRIPTION
**Pull request by jkeck**
Closes #1029 
Closes #1020

### CODE REVIEW

**Comment by cbeer** [comment]
I'm not sure I understand how this fixes our deployment sequencing problem, unless you plan to also revert #1004 too?

**Comment by jkeck** [comment]
@cbeer good catch, sorry, I'm still a little out of it from being sick.

I updated the helper w/ my intention as well as a comment about the behavior.  Let me know if that helps clear things up.

**Comment by cbeer** [comment]
I've also thought of another reason we should probably just choose a new field name -- if the field is used to construct browse categories etc, the new indexing will break them.

**Comment by jkeck** [comment]
Ah, good point. 👍 I'll close this, revert the previous PR, and re-open the issue.

**Pull request closed without merging**
