### PR TITLE
Load our bootstrap focus  color override before bootstrap variables get set

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by camillevilla** [comment]
Part of #1660 

## Before
Screen Shot 2020-02-25 at 2 44 50 PM

## After
focus-styles-on-firefox

**Comment by ggeisler** [comment]
👍 Regarding the TODO, also the primary buttons (in other words, should be all buttons), like the Save changes button in your screenshot. This was part of my original ticket on this topic but that was closed a couple of weeks ago so not sure if the original intent is still clear to everyone: https://github.com/sul-dlss/exhibits/issues/1744

**Comment by camillevilla** [comment]
Slight color tweak after looking at this with Jennifer

## Before
Screen Shot 2020-02-26 at 3 27 22 PM

## After
Screen Shot 2020-02-26 at 3 27 27 PM

**Comment by camillevilla** [comment]
I've split out our TODO to #1776.

**Comment by camillevilla** [comment]
Nevermind! Just had to throw an `!important` on the pile (😱) and this closes #1776 as well. GIF here was taken in Chrome. Green is for native browser focus, blue is Bootstrap focus. 
bootstrap-focus-btns

**Pull request merged**
