### PR TITLE
Add "Market your exhibit" to the site sidebar

### LINKED ISSUE #540: Add sidebar link to "See Also" on exhibits.stanford.edu
Above the link to "Request an exhibit" -- please add a link (with the red Stanford "S" next to it), called:

Market your exhibit
https://consul.stanford.edu/x/2ok1CQ

### PR DESCRIPTION
**Pull request by cbeer**
Fixes #540

### CODE REVIEW

**Comment by mejackreed** [comment]
Looks good. One question though, isn't this just repeating the same link that is above it?

**Comment by camillevilla** [comment]
The Spotlight at Stanford landing page lets you choose between a Confluence page and a PDF:
screen shot 2017-10-27 at 3 21 33 pm

**Comment by caaster** [comment]
I like the link to the Confluence page -- the main page (`https://consul.stanford.edu/display/SUD/Spotlight+at+Stanford+-+Exhibit+Creator+Documentation`) . Because:
1) Then, users can see the other documentation listed. As many chances as we have to remind them the documentation is robust, the better.
2) You'll note that each piece of documentation exists as a Confluence page AND a PDF. This is on purpose, to suit different user preferences, we have provided both options.

**Comment by mejackreed** [comment]
A quick Slack chat with @ggeisler and we decided to hold off on this and defer to @ggeisler . 

An alternative that was discussed:

## Exhibit documentation & marketing

screen shot 2017-10-27 at 7 03 08 pm

**Comment by caaster** [comment]
On second thought. @mejackreed and I had a conversation. Maybe the better option would be to rename the existing link "Exhibit documentation" to be "Exhibit documentation & marketing." It would be good for @ggeisler to weigh in here. Here is a screen shot of the option:
screen shot 2017-10-27 at 7 03 08 pm

**Comment by caaster** [comment]
@camillevilla & @mejackreed Gary agrees with your proposal above. Let's have a single link to "Exhibit documentation & marketing" -- thanks

**Comment by camillevilla** [comment]
Alrighty, I've update the link. @mejackreed want to squash and merge these?

**Pull request merged**
